name: ckpt-release

on:
  push:
    branches: [main]          # run on every push to main
  # or, if you prefer releases:
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest   # or a pinned version, e.g. "1.0.25"

      # Install deps for all workspaces (root of repo)
      - name: Install dependencies
        run: bun install

      # Build ONLY the cli workspace
      - name: Build cli package
        run: bun run build
        working-directory: packages/cli

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      # Publish only the cli workspace
      - name: Publish cli to npm
        run: |
          cd packages/cli
          bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Bun also respects NPM_TOKEN; use whichever secret name you prefer
