name: ckpt-release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun i
      - run: bun run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://npm.pkg.github.com/
          scope: ${{ github.repository_owner }}
      - run: bun i
      - run: bun publish
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
